server:
  port: 0

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: exampleSubscription
    gcp:
      project-id: dz-playground-4711
      credentials:
        location: file:C:\development\spring\ide\ws_gcp\gcp_key.json      
          
